Create TABLE T_LJQCFILE(
[F_ID] integer PRIMARY KEY NOT NULL
,[F_FILENO] integer
,[F_WORKMODE] integer
,[F_SAMPLEMODE] integer
,[F_SPECIESMODE] integer
,[F_BLOODMODE] integer
,[F_ANALYSISMODE] integer
,[F_PREPROCESSMODE] integer
,[F_LOTNO] nvarchar(16)
,[F_EXP_TIME] datetime
,[F_WBC_LOW] float
,[F_WBC_HIGH] float
,[F_LYM_PER_LOW] float
,[F_LYM_PER_HIGH] float
,[F_MID_PER_LOW] float
,[F_MID_PER_HIGH] float
,[F_GRAN_PER_LOW] float
,[F_GRAN_PER_HIGH] float
,[F_LYM_NUM_LOW] float
,[F_LYM_NUM_HIGH] float
,[F_MID_NUM_LOW] float
,[F_MID_NUM_HIGH] float
,[F_GRAN_NUM_LOW] float
,[F_GRAN_NUM_HIGH] float
,[F_RBC_LOW] float
,[F_RBC_HIGH] float
,[F_HGB_LOW] float
,[F_HGB_HIGH] float
,[F_HCT_LOW] float
,[F_HCT_HIGH] float
,[F_MCH_LOW] float
,[F_MCH_HIGH] float
,[F_MCV_LOW] float
,[F_MCV_HIGH] float
,[F_MCHC_LOW] float
,[F_MCHC_HIGH] float
,[F_RDW_SD_LOW] float
,[F_RDW_SD_HIGH] float
,[F_RDW_CV_LOW] float
,[F_RDW_CV_HIGH] float
,[F_PLT_LOW] float
,[F_PLT_HIGH] float
,[F_MPV_LOW] float
,[F_MPV_HIGH] float
,[F_PCT_LOW] float
,[F_PCT_HIGH] float
,[F_PDW_LOW] float
,[F_PDW_HIGH] float
,[F_PLCC_LOW] float
,[F_PLCC_HIGH] float
,[F_PLCR_LOW] float
,[F_PLCR_HIGH] float  
);