#ifndef _LINEEDIT_INTERFACE_H_
#define _LINEEDIT_INTERFACE_H_


#include "widgetinterface.h"


// ±à¼­¿ò¿Ø¼þ
DECLARE_WIDGET_INTERFACE(LineEdit)
DECLARE_WIDGET_INTERFACE(IpLineEdit)
DECLARE_WIDGET_INTERFACE(DateLineEdit)
DECLARE_WIDGET_INTERFACE(TimeLineEdit)
DECLARE_WIDGET_INTERFACE(DigitLineEdit)
DECLARE_WIDGET_INTERFACE(SampleIdLineEdit)


#endif // _LINEEDIT_INTERFACE_H_